<?php
/**
 * Category view template
 * 
 * @author Armin Almuete
 */
 
/**
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<div class="col-main-cat">
<div class="row">
	<div class="page-title category-title large-12 columns">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('share-box-de')->toHtml(); ?>
		<?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
			<a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
		<?php endif; ?>
		<h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
	</div>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>


<div style="float:left" class="show-for-medium-up">
<?php if($_imgUrl): ?>
    <?php echo $_imgHtml ?>
<?php endif; ?>
</div>


<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
    <?php endif; ?>
	
	
<?php if($this->isContentMode()): ?>
	<div id="cat-page-desc-wrapper">
		<?php echo $this->getCmsBlockHtml() ?>
	</div>
	<div class="stripe cpdw"></div>

<?php elseif($this->isMixedMode()): ?>
	<div id="cat-page-desc-wrapper">
		<?php echo $this->getCmsBlockHtml() ?>
	</div>
	<div class="stripe cpdw"></div>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
</div>
