<?php
/**
 * Category view template
 * 
 * @author Armin Almuete
 */
 
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>
	<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
		<div class="form-search row collapse">
			<div class="small-3 right medium-2 large-3 columns">
				<button type="submit" title="<?php echo $this->__('Search') ?>" class="radius tiny button postfix"><span><span><?php echo $this->__('Search') ?></span></span></button>
			</div>
			<div class="small-9 right medium-10 large-8 columns">
				<input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" />
			</div>
			<div id="search_autocomplete" class="search-autocomplete"></div>
			<script type="text/javascript">
			//<![CDATA[
				var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
				searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
			//]]>
			</script>
		</div>
	</form>
