<?php
/**
 * Newsletter subscribe
 * 
 * @author Armin Almuete
 */

/**
 * @var Mage_Newsletter_Block_Subscribe
 */
?>
<div class="block block-subscribe">
    <div class="block-title">
        <span><?php echo $this->__('Newsletter') ?></span>
    </div>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <div class="form-subscribe-header">
                <label for="newsletter"><?php echo $this->__('Sign up for our Newsletter:') ?></label>
            </div>
            <div class="input-box">
               <input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
            </div>
            <div class="actions">
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="radius tiny button"><span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
	
	<script type="text/javascript">
	//<![CDATA[
var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
new Varien.searchForm('newsletter-validate-detail', 'newsletter', '<?php echo $this->helper('newsletter')->__('name@example.com') ?>');
	//]]>
	</script>
	
</div>
