<?php
/**
 * Page html footer
 * 
 * @author Armin Almuete
 */
 
/**
 * @var Mage_Page_Block_Html_Footer $this
 */
?>

<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer-de')->toHtml(); ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer-en')->toHtml(); ?>



<div class="copy-right-container">
	<?php echo $this->getChildHtml('store_language') ?>
	<div class="row">
		<div class="small-12 small-text-center medium-12 medium-uncentered large-12 large-uncentered columns">
			<p class="text-center copy-right">
			<?php echo $this->getCopyright() ?>
			</p>
		</div>
	</div>
</div>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<div class="addthis_sharing_toolbox"></div>

<![CDATA[
  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5746e94b21a8effb" async="async"></script>
]]>

