<?php
/**
 * Page html header
 * 
 * @author Armin Almuete
 */
 
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<script>
function show() {
    AB = document.getElementById('delay');
    AB.style.display = 'inline';
}
setTimeout("show()", 50);
</script>

<?php if($this->getChildHtml('topLinks') || $this->getChildHtml('minicart_head')) : ?>
<div class="top-links-container">
	<div class="row">
		<div class="hide-for-small-only small-12 medium-pull-0 medium-9 large-10 columns">
			<?php echo $this->getChildHtml('topLinks') ?>
		</div>
		<div class="minicart-container small-text-center hide-for-small-only  small-12 medium-text-right  medium-3 large-text-right large-2 columns">
			<?php //echo $this->getChildHtml('store_language') ?>
			<div class="minicart-head-container">
				<?php echo $this->getChildHtml('minicart_head') ?>
			</div>
		</div>
	</div>
</div>
<?php endif; ?>

<div class="header-container row">
    <div class="header small-12 medium-12 large-12 columns">
        <?php if ($this->getIsHomePage()):?>
			<h1 class="logo left text-left small-12 medium-9 large-9 columns">
				<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
					<!--<img data-interchange="[<?php echo $this->getLogoSrc() ?>, (default)], [<?php echo $this->getLogoSrcSmall() ?>, (small)]" alt="Selfhealth - Naturheilkunde-Shop für natürliche Gesundheit" />-->
					<img id="logo-img" class="show-for-small-only" src="<?php echo $this->getLogoSrcSmall() ?>" width="250px" alt="Selfhealth - Naturheilkunde-Shop für natürliche Gesundheit">
					<img id="logo-img" class="show-for-medium-up" src="<?php echo $this->getLogoSrc() ?>" alt="Selfhealth - Naturheilkunde-Shop für natürliche Gesundheit">
				</a>
			</h1>
        <?php else:?>
				<a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
					<!--<img data-interchange="[<?php echo $this->getLogoSrc() ?>, (default)], [<?php echo $this->getLogoSrcSmall() ?>, (small)]" alt="Selfhealth - Naturheilkunde-Shop für natürliche Gesundheit" />-->
					<img id="logo-img" class="show-for-small-only" src="<?php echo $this->getLogoSrcSmall() ?>" width="250px" alt="Selfhealth - Naturheilkunde-Shop für natürliche Gesundheit">
					<img id="logo-img" class="show-for-medium-up" src="<?php echo $this->getLogoSrc() ?>" alt="Selfhealth - Naturheilkunde-Shop für natürliche Gesundheit">
				</a>
        <?php endif?>
        
        <?php echo $this->getChildHtml('topContainer'); ?>
		
		<div id="seal" class="right large-3 medium-3 columns hide-for-small-down">
			<div class="seal-image">
				<div class="founded">&nbsp</div>
				<div class="moneyback">&nbsp</div>
			</div>
		</div>
		
    </div>   
</div>

<?php if($this->getChildHtml('topMenu') || $this->getChildHtml('topSearch')) : ?>
<div class="nav-container row">
	<div class="main-nav">
	<div id="delay">
		<div class="top-menu-container small-12 medium-12 large-8 columns">
			<?php echo $this->getChildHtml('topMenu'); ?>
		</div>
		
		<div class="hide-for-small-only top-search-container small-12 medium-12  large-4 columns">
			<?php echo $this->getChildHtml('topSearch') ?>
		</div>
	</div>
	</div>
</div>
<?php endif; ?>
