<?php
/**
 * Page html notices
 * 
 * @author Armin Almuete
 */
 
/**
 * @var $this Mage_Page_Block_Html_Notices
 */
?>

<?php if ($this->getIsHomePage()):?>
<div class="contain-to-grid custom-notice hide-for-small-only">
	<div class="note-wrapper">
		<h3>Willkommen auf unserer neuen Website!</h3>
		<p>
		Wir arbeiten stark daran die Seite für Sie zu verbessern, und werden nach und nach mehr Inhalt hinzufügen.
		Um jegliches Feedback zur neuen Seite würden wir uns sehr freuen!
		Schicken Sie uns einfach eine kurze Email an: <a href="mailto:feedback@selfhealth.com?Subject=Feedback">feedback@selfhealth.com</a>
		</p>
	</div>
</div>
<?php endif?>

<div class="contain-to-grid foungento-header">
  <nav class="top-bar" data-topbar role="navigation" data-options="">
	<ul class="title-area left">
	  <li class="mobile-bar">
		<a href="<?php echo Mage::getBaseUrl(); ?>" title="<?php echo $this->getLogoAlt() ?>">
			<img id="logo-img-small" alt="Selfhealth - Naturheilkunde-Shop für natürliche Gesundheit">
		</a>
	  </li>
	</ul>
  </nav>
</div>

<?php if ($this->displayNoscriptNotice()): ?>
    <noscript>
        <div class="global-site-notice noscript">
            <div class="notice-inner">
                <p>
                    <strong><?php echo $this->__('JavaScript seems to be disabled in your browser.'); ?></strong><br />
                    <?php echo $this->__('You must have JavaScript enabled in your browser to utilize the functionality of this website.'); ?>
                </p>
            </div>
        </div>
    </noscript>
<?php endif; ?>
<?php if ($this->displayDemoNotice()): ?>
	<div class="row">
		<div class="global-site-notice demo-notice text-center large-12 columns">
			<div class="notice-inner"><p><?php echo $this->__('This is a demo store. Any orders placed through this store will not be honored or fulfilled.') ?></p></div>
		</div>
	</div>
<?php endif; ?>
