<?php
/**
 * Checkout cart
 * 
 * @author Armin Almuete
 */

/**
 * @see Mage_Checkout_Block_Onepage_Progress
 */
?>
<div class="cart ">
    <div class="page-title title-buttons row">
		<div class="small-12 medium-12 large-12 columns">
			<h1><?php echo $this->__('Shopping Cart') ?></h1>
		</div>
        <?php if(!$this->hasError()): ?>
        <div class="small-12 medium-4 large-4 columns">
			<ul class="checkout-types right">
			<?php foreach ($this->getMethods('top_methods') as $method): ?>
				<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
				<li><?php echo $methodHtml; ?></li>
				<?php endif; ?>
			<?php endforeach; ?>
			</ul>
        </div>
        <?php endif; ?>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('form_before') ?>
    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="row">
			<div class="small-12 medium-12 large-12 columns">
				<table id="shopping-cart-table" class="data-table cart-table responsive">
				<?php /* ?>
					<col width="1" />
					<col />
					<col width="1" />
				<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
					<col width="1" />
				<?php endif ?>
				<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<col width="1" />
				<?php endif; ?>
				<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<col width="1" />
				<?php endif; ?>
					<col width="1" />
				<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<col width="1" />
				<?php endif; ?>
				<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<col width="1" />
				<?php endif; ?>
					<col width="1" />
				<?php */ ?>
				<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
					
					<thead>
						<tr>
							<th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
							<th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
							<!-- th rowspan="<?php echo $mergedCells; ?>"></th -->
							<?php /* if ($this->helper('wishlist')->isAllowInCart()) : ?>
							<th rowspan="<?php echo $mergedCells; ?>" class="a-center text-right"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
							<?php endif */?>
							<th class="a-center text-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
							<th rowspan="<?php echo $mergedCells; ?>" class="a-center text-center"><?php echo $this->__('Qty') ?></th>
							<th class="a-center text-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
							<th rowspan="<?php echo $mergedCells; ?>" class="a-center">&nbsp;</th>
						</tr>
						<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
						<tr>
							<th class="a-right text-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
							<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
							<th class="a-right text-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
							<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
						</tr>
						<?php endif; ?>
					</thead>
					
					<tbody>
						<?php foreach($this->getItems() as $_item): ?>
							<?php echo $this->getItemHtml($_item) ?>
						<?php endforeach ?>
					</tbody>
					
					<?php /* ?>
					 <tfoot>
						<tr>
							<td colspan="50" class="a-right">
								<?php if($this->getContinueShoppingUrl()): ?>
									<button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
								<?php endif; ?>
								<button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
								<button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-empty" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
								<!--[if lt IE 8]>
								<input type="hidden" id="update_cart_action_container" />
								<script type="text/javascript">
								//<![CDATA[
									Event.observe(window, 'load', function()
									{
										// Internet Explorer (lt 8) does not support value attribute in button elements
										$emptyCartButton = $('empty_cart_button');
										$cartActionContainer = $('update_cart_action_container');
										if ($emptyCartButton && $cartActionContainer) {
											Event.observe($emptyCartButton, 'click', function()
											{
												$emptyCartButton.setAttribute('name', 'update_cart_action_temp');
												$cartActionContainer.setAttribute('name', 'update_cart_action');
												$cartActionContainer.setValue('empty_cart');
											});
										}

									});
								//]]>
								</script>
								<![endif]-->
							</td>
						</tr>
					</tfoot>
					<?php */ ?>
					
				</table>
				<script type="text/javascript">decorateTable('shopping-cart-table')</script>
			</div>
		</div>
    </form>
    
    <div class="cart-collaterals row">
		<div class="col-1 large-12 columns">
			<?php echo $this->getChildHtml('crosssell') ?>
		</div>
        <div class="col2-set large-8 columns">
			<?php /* Extensions placeholder */ ?>
			<?php echo $this->getChildHtml('checkout.cart.extra') ?>
			<?php echo $this->getChildHtml('coupon') ?>
			<?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
        </div>
        <div class="totals large-4 columns">
            <?php echo $this->getChildHtml('totals'); ?>
            <?php if(!$this->hasError()): ?>
            <ul class="checkout-types right">
            <?php foreach ($this->getMethods('methods') as $method): ?>
                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                <li><?php echo $methodHtml; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </div>
    </div>
    
</div>
