<?php
/**
 * Shoping cart sidebar
 *
 * @var Mage_Checkout_Block_Cart_Minicart $this
 */
?>

<?php
$_cartQty = $this->getSummaryCount();
if(empty($_cartQty)) {
    $_cartQty = 0;
}
?>
<div id="minicart-error-message" class="minicart-message"></div>
<div id="minicart-success-message" class="minicart-message"></div>

<div class="minicart-wrapper">

    <p class="block-subtitle small-text-center medium-text-left large-text-left">
        <?php echo $this->__('Shopping Bag %s Item(s)', $_cartQty) ?>
		<a class="close-reveal-modal">&#215;</a>
    </p>

    <?php $_items = $this->getRecentItems() ?>
    <?php $countItems = count($_items); ?>
	<?php if($countItems): ?>
		<div class="row">
			<div id="minicart-widgets" class="large-12 columns">
				<?php echo $this->getChildHtml('cart_promotion') ?>
			</div>
			
			<div class="cart-subtotal large-12 columns">

				<div class="subtotal small-text-center medium-text-right large-text-right">
					<?php if ($this->canApplyMsrp()): ?>
						<span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
					<?php else: ?>
						<?php echo $this->__('Cart Subtotal: ') ?><?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
						<?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
							<br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
						<?php endif; ?>
					<?php endif; ?>
				</div>

				<?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
					<div class="small-text-center medium-text-right large-text-right">
						<ul class="checkout-types minicart">
							<?php echo $this->getChildHtml('extra_actions') ?>
							<li>
								<a title="<?php echo $this->__('Checkout') ?>" class="radius tiny button checkout-button" href="<?php echo $this->getCheckoutUrl() ?>">
									<?php echo $this->__('Checkout') ?>
								</a>
								
								<a class="radius tiny button cart-link" href="<?php echo $this->getUrl('checkout/cart'); ?>">
									<?php echo $this->__('View Shopping Cart'); ?>
								</a>
							</li>
						</ul>
					</div>
				<?php endif ?>



			</div>
		</div>
	<?php endif; ?>



    <?php if($countItems): ?>
        <div>
            <ul id="cart-sidebar" class="mini-products-list small-block-grid-1 medium-block-grid-2 large-block-grid-4">
                <?php foreach($_items as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach; ?>
            </ul>
        </div>
        <script type="text/javascript">
            decorateList('cart-sidebar', 'none-recursive');
            jQuery('document').ready(function() {
                var minicartOptions  = {
                    formKey:           "<?php echo $this->getFormKey();?>"
                }
                var Mini = new Minicart(minicartOptions);
                Mini.init();
            });
        </script>

        
        <div class="row">
			<div id="minicart-widgets" class="large-12 columns">
				<?php echo $this->getChildHtml('cart_promotion') ?>
			</div>
			
			<div class="cart-subtotal large-12 columns">
				<div class="subtotal small-text-center medium-text-right large-text-right">
					<?php if ($this->canApplyMsrp()): ?>
						<span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
					<?php else: ?>
						<?php echo $this->__('Cart Subtotal: ') ?><?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
						<?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
							<br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
						<?php endif; ?>
					<?php endif; ?>
				</div>
			
				<?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
					<div class="small-text-center medium-text-right large-text-right">
						<ul class="checkout-types minicart">
							<?php echo $this->getChildHtml('extra_actions') ?>
							<li>
								<a title="<?php echo $this->__('Checkout') ?>" class="radius tiny button checkout-button" href="<?php echo $this->getCheckoutUrl() ?>">
									<?php echo $this->__('Checkout') ?>
								</a>
								
								<a class="radius tiny button cart-link" href="<?php echo $this->getUrl('checkout/cart'); ?>">
									<?php echo $this->__('View Shopping Cart'); ?>
								</a>
							</li>
						</ul>
					</div>
				<?php endif ?>
			</div>
		</div>

    <?php else: ?>
        <p class="empty small-text-center medium-text-center large-text-center"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
    <?php endif ?>
</div>
