<?php
/**
 * Product list template
 *
 * @author Armin Almuete
 * 
 */
 
/**
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol id="products-list" class="products-list small-block-grid-1 medium-block-grid-3 large-block-grid-1">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item">
            
            <div class="row">
				<div class="large-5 columns">
					<?php // Product Image ?>
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(600); ?>" width="600" height="600" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
					<?php // Product description ?>
				</div>
				<div class="product-shop large-7 columns">
					<div class="f-fix">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
						<?php /*if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product) ?>
						<?php endif; */?>
						<?php echo $this->getPriceHtml($_product, true) ?>
						<?php if($_product->isSaleable()): ?>
							<p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="radius tiny button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
						<div class="desc std">
							<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
						</div>
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow()) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
							<?php endif; ?>
							<!--<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
								<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
							<?php endif; ?>-->
						</ul>
					</div>
				</div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <div class="list-items row">
		<div class="small-12 medium-12 large-12 columns">
			<ul class="products-grid small-block-grid-2 medium-block-grid-3 large-block-grid-3">
			<?php $i=0; foreach ($_productCollection as $_product): ?>
				<?php /* if ($i++%$_columnCount==0): ?>
				<ul class="products-grid small-block-grid-2 medium-block-grid-3 large-block-grid-3">
				<?php endif */ ?>
					<li class="list-items item small-text-center medium-text-left large-text-left">
					<div class="list-item-wrapper">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
						<div class="list-image-wrapper">
						<div class="list-image">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(600); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
						</div>
						</div>
						</a>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
						<div class="list-short-desc">
						<?php
							$my_product = Mage::getModel('catalog/product')->load($_product->getId());
							echo $my_product->getShortDescription();
						?>
						</div>
						<?php /* if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
						<?php endif; */ ?>
						<?php echo $this->getPriceHtml($_product, true) ?>
						<div class="force-bottom actions small-text-center medium-text-left large-text-left">
							<?php if($_product->isSaleable()): ?>
								<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="radius tiny  button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
							<?php else: ?>
								<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
							<?php endif; ?>
							<ul class="add-to-links">
								<?php if ($this->helper('wishlist')->isAllow()) : ?>
									<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
								<?php endif; ?>
								<!--<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
									<li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
								<?php endif; ?>-->
							</ul>
						</div>
						<div class="stripe"></div>
						</div>
					</li>
				<?php /*if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
				</ul>
				<?php endif */ ?>
				<?php endforeach ?>
			</ul>
			</div>
        </div>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
