<?php
/**
 * Product view template
 *
 * @author Armin Almuete
 * 
 */
 
/**
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view" itemscope itemtype="http://schema.org/Product">
    <div class="product-essential row">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
		
		<div class="product-name large-7 large-right hide-for-medium-up">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('share-box-de')->toHtml(); ?>
            </div>
        
        <div class="product-img-box small-12 small-centered medium-6 medium-uncentered large-5 columns">
            <?php echo $this->getChildHtml('media') ?>
        </div>
		
		
		
		<div class="product-shop small-12 medium-6 large-7 columns end">
		
			<h1 itemprop="name"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
			

			<?php if($_product->isAvailable()): ?>
				<div class="no-display" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
					<!--<span itemprop="price"><?php echo Mage::helper('core')->currency($_product->getFinalPrice()); ?></span>-->
					<span itemprop="price"><?php echo $_product->getFinalPrice(); ?></span>
					<span itemprop="priceCurrency">€</span>
					<link itemprop="availability" href="http://schema.org/InStock" />
				</div>
			<?php endif; ?>

            
            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?>

            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php elseif (!$_product->isSaleable()): ?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
            <?php endif; ?>
			
			<div class="row">

			
				
				<?php if ($_product->isSaleable() && $this->hasOptions()):?>
					<div class="container1 large-6 columns">
						<?php echo $this->getChildChildHtml('container1', '', true, true) ?>
					</div>
				<?php endif;?>

				<?php if ($_product->getShortDescription()):?>
					<div class="container2 large-12 columns">
						<h2><?php echo $this->__('Quick Overview') ?></h2>
						<div class="std" itemprop="description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
					</div>
				<?php endif;?>	


            </div>

            <?php echo $this->getChildHtml('other');?>

            

        </div>



    </form>
	
	<div class="stripe small-12 medium-12 large-12 columns">
	</div>
	
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>




    <div class="product-collateral row">
	<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php echo "box-{$alias}"?> large-12 columns">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('share-box-de')->toHtml(); ?>
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
	<?php endforeach;?>
        <?php //echo $this->getChildHtml('product_additional_data') ?>
    </div>

	<div class="row">
		<div class="box-collateral box-up-sell large-12 columns">
			<?php echo $this->getChildHtml('upsell_products') ?>
		</div>
	</div>

</div>
