<?php
/**
 * Customer account dashboard address
 * 
 * @author Armin Almuete
 */

/**
 * @var Mage_Customer_Block_Account_Dashboard_Address
 */
?>
<div class="col2-set">
    <div class="box">
        <div class="box-title">
            <h3><?php echo $this->__('Address Book') ?></h3>
            <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
        </div>
        <div class="box-content row">
            <div class="col-1 small-12 medium-6 large-6 columns">
                <h4><?php echo $this->__('Default Billing Address') ?></h4>
                <address>
                    <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
                    <a class="button radius tiny" href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </address>
            </div>
            <div class="col-2 small-12 medium-6 large-6 columns">
                <h4><?php echo $this->__('Default Shipping Address') ?></h4>
                <address>
                    <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
                    <a class="button radius tiny" href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </address>
            </div>
        </div>
    </div>
</div>
